version: "3"

services:

  mongo:
    image: mongo:4.2.7
    container_name: powerchain-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - .data/mongodb:/data/db
      - ./script/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: powerchain-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - .config/mosquitto:/mosquitto/config

  ganache:
    image: trufflesuite/ganache-core:latest
    container_name: powerchain-ganache
    ports:
      - 8545:8545

  server:
    image: dkakunsi/powerchain-server:latest
    build:
      context: ../powerchain-server
      dockerfile: Dockerfile
    container_name: powerchain-server
    ports:
      - 5001:5001
    environment:
      - MQTT_HOST=mosquitto
      - MONGO_HOST=mongo
      - ETHEREUM_HOST=ganache
    depends_on:
      - mosquitto
      - mongo
      - ganache

  peer1:
    image: dkakunsi/powerchain-peer:latest
    build:
      context: ../powerchain-peers
      dockerfile: Dockerfile
    container_name: powerchain-peer-1
    environment:
      - PEER_ID=65baffd14f7816879c0a4273
      - MQTT_HOST=mosquitto
      - GENERATED_ENERGY=2.002
    volumes:
      - ./file/peer1.txt:/opt/powerchain/beban.txt
    depends_on:
      - mosquitto

  peer2:
    image: dkakunsi/powerchain-peer:latest
    container_name: powerchain-peer-2
    environment:
      - PEER_ID=65bb00104f7816879c0a4274
      - MQTT_HOST=mosquitto
      - GENERATED_ENERGY=0
    volumes:
      - ./file/peer2.txt:/opt/powerchain/beban.txt
    depends_on:
      - mosquitto

  peer3:
    image: dkakunsi/powerchain-peer:latest
    container_name: powerchain-peer-3
    environment:
      - PEER_ID=65bb005a4f7816879c0a4275
      - MQTT_HOST=mosquitto
      - GENERATED_ENERGY=0
    volumes:
      - ./file/peer3.txt:/opt/powerchain/beban.txt
    depends_on:
      - mosquitto

  peer4:
    image: dkakunsi/powerchain-peer:latest
    container_name: powerchain-peer-4
    environment:
      - PEER_ID=65bb00be4f7816879c0a4276
      - MQTT_HOST=mosquitto
      - GENERATED_ENERGY=0
    volumes:
      - ./file/peer4.txt:/opt/powerchain/beban.txt
    depends_on:
      - mosquitto

  peer5:
    image: dkakunsi/powerchain-peer:latest
    container_name: powerchain-peer-5
    environment:
      - PEER_ID=65bb00d94f7816879c0a4277
      - MQTT_HOST=mosquitto
      - GENERATED_ENERGY=0
    volumes:
      - ./file/peer5.txt:/opt/powerchain/beban.txt
    depends_on:
      - mosquitto

  peer6:
    image: dkakunsi/powerchain-peer:latest
    container_name: powerchain-peer-6
    environment:
      - PEER_ID=65bb00fe4f7816879c0a4278
      - MQTT_HOST=mosquitto
      - GENERATED_ENERGY=2.962962963
    volumes:
      - ./file/peer6.txt:/opt/powerchain/beban.txt
    depends_on:
      - mosquitto

  peer7:
    image: dkakunsi/powerchain-peer:latest
    container_name: powerchain-peer-7
    environment:
      - PEER_ID=65bb01314f7816879c0a4279
      - MQTT_HOST=mosquitto
      - GENERATED_ENERGY=0
    volumes:
      - ./file/peer7.txt:/opt/powerchain/beban.txt
    depends_on:
      - mosquitto

  peer8:
    image: dkakunsi/powerchain-peer:latest
    container_name: powerchain-peer-8
    environment:
      - PEER_ID=65bb01544f7816879c0a427a
      - MQTT_HOST=mosquitto
      - GENERATED_ENERGY=0.202222222
    volumes:
      - ./file/peer8.txt:/opt/powerchain/beban.txt
    depends_on:
      - mosquitto

  peer9:
    image: dkakunsi/powerchain-peer:latest
    container_name: powerchain-peer-9
    environment:
      - PEER_ID=65bb017c4f7816879c0a427b
      - MQTT_HOST=mosquitto
      - GENERATED_ENERGY=0
    volumes:
      - ./file/peer9.txt:/opt/powerchain/beban.txt
    depends_on:
      - mosquitto

  peer10:
    image: dkakunsi/powerchain-peer:latest
    container_name: powerchain-peer-10
    environment:
      - PEER_ID=65bb01994f7816879c0a427c
      - MQTT_HOST=mosquitto
      - GENERATED_ENERGY=2.592592593
    volumes:
      - ./file/peer10.txt:/opt/powerchain/beban.txt
    depends_on:
      - mosquitto
