version: "3"

services:

  mongo:
    image: mongo:4.2.7
    container_name: powerchain-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - .data/mongodb:/data/db
      - ./script/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: powerchain-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - .config/mosquitto:/mosquitto/config

  ganache:
    image: trufflesuite/ganache-core:latest
    container_name: powerchain-ganache
    ports:
      - 8545:8545

  server:
    image: powerchain/server:latest
    build:
      context: ../powerchain-server
      dockerfile: Dockerfile
    container_name: powerchain-server
    ports:
      - 5001:5001
    environment:
      - MQTT_HOST=mosquitto
      - MONGO_HOST=mongo
      - ETHEREUM_HOST=ganache

  peer1:
    image: powerchain/peer:latest
    build:
      context: ../powerchain-peers
      dockerfile: Dockerfile
    container_name: powerchain-peer-1
    environment:
      - PEER_ID=651a0abda95812bb9bdd973a
      - MQTT_HOST=mosquitto

  peer2:
    image: powerchain/peer:latest
    build:
      context: ../powerchain-peers
      dockerfile: Dockerfile
    container_name: powerchain-peer-2
    environment:
      # change with peer ObjectId
      - PEER_ID=peer2
      - MQTT_HOST=mosquitto

  peer3:
    image: powerchain/peer:latest
    build:
      context: ../powerchain-peers
      dockerfile: Dockerfile
    container_name: powerchain-peer-3
    environment:
      # change with peer ObjectId
      - PEER_ID=peer3
      - MQTT_HOST=mosquitto

  peer4:
    image: powerchain/peer:latest
    build:
      context: ../powerchain-peers
      dockerfile: Dockerfile
    container_name: powerchain-peer-4
    environment:
      # change with peer ObjectId
      - PEER_ID=peer4
      - MQTT_HOST=mosquitto

  peer5:
    image: powerchain/peer:latest
    build:
      context: ../powerchain-peers
      dockerfile: Dockerfile
    container_name: powerchain-peer-5
    environment:
      # change with peer ObjectId
      - PEER_ID=peer5
      - MQTT_HOST=mosquitto
