version: "3"

services:

  mongo:
    image: mongo:4.2.7
    container_name: powerchain-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - .data/mongodb:/data/db
      - ./script/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: powerchain-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - .config/mosquitto:/mosquitto/config

  ganache:
    image: trufflesuite/ganache-core:latest
    container_name: powerchain-ganache
    ports:
      - 8545:8545