version: "3"

services:

  mongo:
    image: mongo:4.2.7
    container_name: powerchain-mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    ports:
      - "27017:27017"
    volumes:
      - .data/mongodb:/data/db
      - ./script/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mosquitto:
    image: eclipse-mosquitto:2.0.18
    container_name: powerchain-mosquitto
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - .config/mosquitto:/mosquitto/config

  ganache:
    image: trufflesuite/ganache-core:latest
    container_name: powerchain-ganache
    ports:
      - 8545:8545

  server:
    image: dkakunsi/powerchain-server:latest
    build:
      context: ../powerchain-server
      dockerfile: Dockerfile
    container_name: powerchain-server
    ports:
      - 5001:5001
    environment:
      - MQTT_HOST=mosquitto
      - MONGO_HOST=mongo
      - ETHEREUM_HOST=ganache
    depends_on:
      - mosquitto
      - mongo
      - ganache

  peer1:
    image: dkakunsi/powerchain-peer:latest
    build:
      context: ../powerchain-peers
      dockerfile: Dockerfile
    container_name: powerchain-peer-1
    environment:
      - PEER_ID=658e650fc02267fe16d36f8d
      - MQTT_HOST=mosquitto
    depends_on:
      - mosquitto

  peer2:
    image: dkakunsi/powerchain-peer:latest
    container_name: powerchain-peer-2
    environment:
      - PEER_ID=658e6535c02267fe16d36f8e
      - MQTT_HOST=mosquitto
    depends_on:
      - mosquitto

  peer3:
    image: dkakunsi/powerchain-peer:latest
    container_name: powerchain-peer-3
    environment:
      - PEER_ID=658e655ec02267fe16d36f8f
      - MQTT_HOST=mosquitto
    depends_on:
      - mosquitto

  # peer4:
  #   image: dkakunsi/powerchain-peer:latest
  #   container_name: powerchain-peer-4
  #   environment:
  #     - PEER_ID=651a0adda95812bb9bdd973c
  #     - MQTT_HOST=mosquitto
  #   depends_on:
  #     - mosquitto

  # peer5:
  #   image: dkakunsi/powerchain-peer:latest
  #   container_name: powerchain-peer-5
  #   environment:
  #     - PEER_ID=651a0aeca95812bb9bdd973d
  #     - MQTT_HOST=mosquitto
  #   depends_on:
  #     - mosquitto

  # peer6:
  #   image: dkakunsi/powerchain-peer:latest
  #   container_name: powerchain-peer-6
  #   environment:
  #     - PEER_ID=651a0b03a95812bb9bdd973e
  #     - MQTT_HOST=mosquitto
  #   depends_on:
  #     - mosquitto

  # peer7:
  #   image: dkakunsi/powerchain-peer:latest
  #   container_name: powerchain-peer-7
  #   environment:
  #     - PEER_ID=651a0b1ba95812bb9bdd973f
  #     - MQTT_HOST=mosquitto
  #   depends_on:
  #     - mosquitto

  # peer8:
  #   image: dkakunsi/powerchain-peer:latest
  #   container_name: powerchain-peer-8
  #   environment:
  #     - PEER_ID=651a46f25d00604a3eb03d6e
  #     - MQTT_HOST=mosquitto
  #   depends_on:
  #     - mosquitto

  # peer9:
  #   image: dkakunsi/powerchain-peer:latest
  #   container_name: powerchain-peer-9
  #   environment:
  #     - PEER_ID=peer9
  #     - MQTT_HOST=mosquitto
  #   depends_on:
  #     - mosquitto

  # peer10:
  #   image: dkakunsi/powerchain-peer:latest
  #   container_name: powerchain-peer-10
  #   environment:
  #     - PEER_ID=peer10
  #     - MQTT_HOST=mosquitto
  #   depends_on:
  #     - mosquitto
